In [12]:
import numpy as np # Importa biblioteca
array = np.random.randint(100, size=(10, 300))/100 # Detrmina o número de linhas e colunas
print(array) # Imprime matriz

[[0.98 0.32 0.58 ... 0.91 0.22 0.57]
 [0.9  0.22 0.73 ... 0.9  0.55 0.4 ]
 [0.41 0.69 0.13 ... 0.48 0.04 0.79]
 ...
 [0.95 0.65 0.2  ... 0.37 0.71 0.19]
 [0.58 0.5  0.41 ... 0.16 0.84 0.39]
 [0.4  0.05 0.31 ... 0.65 0.08 0.88]]


In [13]:
import pandas as pd # Importa biblioteca
ma = pd.DataFrame(array) # Converte array em dataframe
ma.to_csv('matrizaleatoria.csv', header=None) # Salva como CSV